### PR TITLE
Add Participants template

### PR DESCRIPTION
**Pull request by parhaml**
Adds a proposed template to encourage users to fork the repo and practice their PR flow.

### CODE REVIEW

**Comment by ericwburden** [comment]
I think this looks good. Any objections?

**Review by ericwburden — DISMISSED** [review]
I think this looks good. Also a good way to keep track of participants! :smile:

**Comment by xanderyzwich** [comment]
I like this idea, but I'd prefer that we use markdown links.

Ex:
[Corey McCarty](https://github.com/xanderyzwich)

**Comment by parhaml** [comment]
> I like this idea, but I'd prefer that we use markdown links.
> 
> Ex:
> `[Corey McCarty](https://github.com/xanderyzwich)` displays as
> [Corey McCarty](https://github.com/xanderyzwich)

Updated @xanderyzwich thanks

**Review by ericwburden — APPROVED** [review]
+1

**Review by xanderyzwich — APPROVED** [review]
I like it

**Pull request merged**
