### PR TITLE
Python | Pascal's Triangle

### PR DESCRIPTION
**Pull request by xcelr8**
#338 

# Language

Python

# Challenge

Pascal's Triangle

### CODE REVIEW

**Comment by ericwburden** [comment]
Can I safely assume you'd prefer to have this PR reviewed during October?

**Comment by xcelr8** [comment]
> Can I safely assume you'd prefer to have this PR reviewed during October?

Yes. I don't understand the next Tuesday mob meeting schedule and the workflow etc. so whenever is the apt time to review it

**Comment by ericwburden** [comment]
Oh, sorry, I assumed you were using this as a PR for Hacktoberfest. If not, then we can go ahead and review.

**Comment by xcelr8** [comment]
> PR for Hacktoberfest.
is there a difference in reviewing it now or for hacktoberfest? I don't really mind waiting 10 days if its gonna add value to hactoberfest

**Comment by ericwburden** [comment]
Nah, don't worry about it. I just assumed that's what you were doing. If you're interested in Hacktoberfest, you can find out more [here](https://hacktoberfest.com/). We'll have more challenges up for it as well.

**Review by ericwburden — APPROVED** [review]
Works for all the test cases (and a few I just made up 😁)

**Comment by ericwburden** [comment]
I like the extra functions to print out the triangle.

**Comment by xcelr8** [comment]
> I like the extra functions to print out the triangle.

Thanks, I actually misunderstood the bonus part of the problem at first that requested the 2D array and thought it required the triangle to be printed as a 2D figure. Later when I realised the 2D array was the bonus question I added that too and left the triangle function in there coz why not xD

**Review by drkennetz — APPROVED** [review]

**Pull request merged**
