### PR TITLE
Merge pull request #1 from codeconnector/main

### PR DESCRIPTION
**Pull request by mic-k-r**
Use variable over tmpfile for test results (#19)

### CODE REVIEW

**Comment by ericwburden** [comment]
I don't think this was intentional

**Comment by mic-k-r** [comment]
Hey! It actually was, but I have no idea what I’m doing when it comes to
Git if you haven’t already noticed. Good learning experience- thank you!

**Comment by ericwburden** [comment]
No worries! Happy to help walk you through it if you'd like.

**Comment by mic-k-r** [comment]
Hey Eric,

That's a really kind offer, that would be great!

**Pull request closed without merging**
