### PR TITLE
2020-04-20 Challenge Solution

### PR DESCRIPTION
**Pull request by Aaronlonin**
Change-Id: I9fda0d239cce0579b88356e8ff3d1b6995c02b38

### CODE REVIEW

**Review by ericwburden — APPROVED** [review]
Looks good to me. Check the `test-it.sh` file if you're curious about how the test runner compiles and runs the tests without an IDE project setup (and integrates the standalone JUnit .jar).

**Comment by Aaronlonin** [comment]
Thanks Eric! Yes, I ran it too and got the following result:

.
+-- JUnit Jupiter [OK]
'-- JUnit Vintage [OK]

Test run finished after 28 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]

**Comment by ericwburden** [comment]
Huh, that is odd. I wonder why it didn't find any tests...

**Review by drkennetz — DISMISSED** [review]
Looks good!

**Comment by Aaronlonin** [comment]
I noticed I missed pushing the imports for HashMap and Map
Corrected in my forked repository. I don't think it's worth a new pull request tho :).

**Review by ericwburden — APPROVED** [review]

**Review by parhaml — APPROVED** [review]

**Pull request merged**
