### PR TITLE
Drkennetz box in a box

### PR DESCRIPTION
**Pull request by drkennetz**
my go solution to box-in-a-box. Since go doesn't really do oop per se, I've created my own types with receiver functions to construct the rectangle and overlap. Maybe it could be implemented differently

### CODE REVIEW

**Review by birenderjit — COMMENTED** [review]
I dont think we will be able to run the test as this is package main. I was not able to run the tests for the last solution you submitted and that also was package main.

**Review by ericwburden — COMMENTED** [review]
The code looks great! I have the same question I had for @birenderjit, and maybe just in general for solutions that require multiple files: Do we think it would be cleaner to add those files to a folder, like `solutions/drkennetz.go/<files go here>`?

**Comment by drkennetz** [comment]
I actually think that's a great idea. Let me refactor. @birenderjit I didn't know you couldn't run the tests as they work on my local machine. That is good feedback. Should I change the package name to solutions?

**Review by ericwburden — APPROVED** [review]
Love it!

**Comment by drkennetz** [comment]
Updated directory structure to be `solutions/go/drkennetz/*.go`

**Review by ericwburden — APPROVED** [review]

**Review by birenderjit — APPROVED** [review]

**Pull request merged**
