### PR TITLE
Harrison's Javascript solution to blast-from-past

### PR DESCRIPTION
**Pull request by HARRIFIED**
# Language

What language was used for the solution? Javascript

# Challenge

What is the name of the challenge being completed? blast-from-past

### CODE REVIEW

**Review by drkennetz — APPROVED** [review]
Looks good to me! Thanks for the PR.

**Comment by xanderyzwich** [comment]
@HARRIFIED we need you to move your solution down into a directory with your github username
solutions/javascript/harrified/solution.js

**Comment by HARRIFIED** [comment]
@xanderyzwich what should I do

**Comment by xanderyzwich** [comment]
- copy solution.js into notepad.
- create javascript directory in solutions directory, 
- create harrified directory inside that one. 
- Then create solution.js in that directory with content from notepad
- from command line `git revert 2960881b7c851e47d904e6fae7a27187fd022f9a`
- then git add the new solutions/javascript/harrified/solution.js
- commit
- push

**Review by drkennetz — CHANGES_REQUESTED** [review]
Sorry - missed the location of the file. Follow @xanderyzwich 's instructions and I'll re-review

**Comment by drkennetz** [comment]
@HARRIFIED if you need help on the instructions, feel free to ping us! No worries at all.

**Review by drkennetz — APPROVED** [review]

**Pull request merged**
