### PR TITLE
 solution

### PR DESCRIPTION
**Pull request by milaguileras**

### CODE REVIEW

**Review by xanderyzwich — COMMENTED** [review]
There are some IntelliJ files in here, I'll need to delete those.

**Review by ericwburden — CHANGES_REQUESTED** [review]
Looks like you've got a few extra files in your commit. You want just `challenges/2021-05-11-nonconstructible-change/solutions/java/milaguileras/milaguileras.java`. With your WIP branch checked out, you can get a list of changed files with `git diff --name-only main`.  You can then remove the unnecessary files from the repo with `git rm --cached <filename>`. The `--cached` flag is VERY important, without it the file is removed from the repo AND deleted from your machine.

Take out all the files except for your submitted solutions file, and you'll be good to go!

**Comment by ericwburden** [comment]
Apologies for making that sound like it was a simple fix in Git. Turned out to be a bit of a bear (mostly because I neglected to update the PR branch and rebase it on top of main *before* I started removing files...). All cleaned up now!

**Comment by ericwburden** [comment]
For posterity, what I *should* have done was:

- Update the main branch: `git checkout main` -> `git fetch upstream` -> `git merge upstream/main`
- Rebase the solution commit: `git checkout milaguileras-wip` -> `git rebase main`
- Remove the changed files we didn't want to commit to the repo: `git rm -r --cached <files to remove>`
- Check to be sure I've only got the solutions file in the commit: `git diff --name-status main`
- Commit and push: `git commit -m "<commit message>"` -> `git push`

**Review by ericwburden — APPROVED** [review]

**Review by birenderjit — APPROVED** [review]

**Pull request merged**
