### PR TITLE
2021 04 13 submit challenge

### PR DESCRIPTION
**Pull request by ericwburden**
Adds the project shell for the 2021-04-13 challenge, Single and Ready to Mingle. Project shell is for a JavaScript project using npm 6+.

### CODE REVIEW

**Review by parhaml — DISMISSED** [review]
Works for me
Screen Shot 2021-04-08 at 5 09 52 PM


after npm install:
Screen Shot 2021-04-08 at 5 11 39 PM



should we `.gitignore` `node_modules`

**Comment by ericwburden** [comment]
Thanks for that run. It looks like it wasn't exiting properly when the tests didn't run. I've updated it to properly exit now.

**Comment by ericwburden** [comment]
As for `node_modules`: I think so. There's a LOT in there, and you can build it with npm install. May need to add the npm install instruction, though.

**Review by parhaml — APPROVED** [review]

**Review by birenderjit — APPROVED** [review]

**Comment by drkennetz** [comment]
The dependencies for npm are no joke! Working on this bad boy

**Comment by ericwburden** [comment]
I figure that's what comes from trying to make JS into a real boy. ;)

**Pull request merged**
