### PR TITLE
Submit challenge setup for 2022-03-15 meetup

### PR DESCRIPTION
**Pull request by ericwburden**
Setup for JavaScript challenge, Longest Common Prefix

### CODE REVIEW

**Review by mrumiker — DISMISSED** [review]
Looks great! I'd like to see a test case where all the input is something like ["apple", "apple", "apple"] and the function returns "apple"

**Comment by mrumiker** [comment]
And what if that one that returns "cast" also has "cast" as one of the words?

**Comment by ericwburden** [comment]
Added tests, and marked`run-tests` as executable (oops!)

**Comment by ericwburden** [comment]
Added a 'large' test as well, to discourage any sort of "compare each item to every other item" approach.

**Review by drkennetz — APPROVED** [review]

**Review by xanderyzwich — APPROVED** [review]

**Pull request merged**
