### PR TITLE
2021 11 09 ericwburden look and say sequence meetup solution

### PR DESCRIPTION
**Pull request by ericwburden**
# Language

Rust

# Challenge

Look and Say Numbers

### CODE REVIEW

**Comment by ericwburden** [comment]
I might have gone overboard in the "Make it right" pass...

**Review by drkennetz — APPROVED** [review]
The comments are super helpful. Thanks! Looks good to me.

**Comment by drkennetz** [comment]
> I might have gone overboard in the "Make it right" pass...

You definitely committed to "making it right" 👍

**Comment by ericwburden** [comment]
Sorry, I couldn't resist updating it once I realized it could be simplified *a lot* by using `itertools`.

**Review by xanderyzwich — APPROVED** [review]

**Review by drkennetz — APPROVED** [review]

**Pull request merged**
